sudo: false
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '10'

git:
  depth: 1

stages:
  - basic
  - compatibility
  - name: deploy
    if: branch = master AND type = push

# before_install:
#   - curl -o- -L https://yarnpkg.com/install.sh | bash
#   - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive --no-lockfile
  - yarn global add lerna

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: basic
      name: 'Conventional Commits, Lint and Fixed Dependencies'
      install:
        - yarn install --non-interactive
        - yarn add -WD codecov
      script:
        - commitlint-travis && echo "✅ Commitlint passed"
        - lerna run lint --concurrency 4
        - lerna run test:coverage --concurrency 1
      after_success:
        - test "$TRAVIS_BRANCH" = "master" && ./node_modules/.bin/codecov
        - test "$TRAVIS_BRANCH" = "master" && npm install -g codacy-coverage
        - test "$TRAVIS_BRANCH" = "master" && lerna run codacy:transmit-coverage

    - stage: compatibility
      name: 'Floating Dependencies'
      script: lerna run test
    - &ui-kit-test-one
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
      script:
        - cd packages/ui-kit
        - lerna run try:one --concurrency 1
    - <<: *ui-kit-test-one
      node_js: 8
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - <<: *ui-kit-test-one
      env: EMBER_TRY_SCENARIO=ember-beta
    - <<: *ui-kit-test-one
      env: EMBER_TRY_SCENARIO=ember-release
    - <<: *ui-kit-test-one
      env: EMBER_TRY_SCENARIO=ember-canary
    - <<: *ui-kit-test-one
      env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - stage: deploy
      name: 'Publish to npm'
      script: .travis/_publish.sh
