jobs:
  # - job: windows
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   steps:
  #     - template: .azure/setup-project.yml
  #     - script: yarn test
  #       displayName: Run Tests

  - job: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/setup-project.yml
      - script: tar -cf snap-doc.tar ./*
        displayName: 'Preparing Artifact'
      - task: CopyFiles@2
        inputs:
          contents: 'snap-doc.tar'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: linux-build
  
  - job: windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .azure/setup-project.yml
      - script: yarn test
  
  - job: linux_floating
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/setup-project.yml
        installCommand: yarn install --non-interactive --no-lockfile
      - script: |
          yarn test
        displayName: 'Run Tests'

  - job: linux_fixed
    dependsOn: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/linux-build-job.yml
      - script: |
          yarn test
        displayName: 'Run Tests'

  - job: lint
    dependsOn: linux_build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/linux-build-job.yml
      - script: |
          yarn lerna run lint:ts --parallel
          yarn lerna run lint:js --parallel
          yarn lerna run lint:hbs --parallel
          yarn lerna run lint:md --parallel
        displayName: 'Lint'

